"""Harness scenario catalog."""

from __future__ import annotations

from pathlib import Path
from typing import Any

_FIXTURES = Path(__file__).resolve().parents[2] / "tests" / "fixtures"

SCENARIOS: dict[str, dict[str, Any]] = {
    "smoke_write_file": {
        "description": "Create harness_smoke.py",
        "surface": "code",
        "template_id": "tpl.code.smoke",
        "job_type": "code_edit",
        "objective": (
            "Create harness_smoke.py with print('HARNESS_OK') using write_file. "
            "Then set final_report when done."
        ),
        "tools": ["read_file", "write_file", "list_dir", "grep"],
        "acceptance": {
            "check_file_glob": "**/harness_smoke.py",
            "file_contains": "HARNESS_OK",
        },
    },
    "learn_syllabus_files": {
        "description": "Build deep syllabus from course materials",
        "surface": "learn",
        "template_id": "tpl.learn.syllabus_files",
        "job_type": "learn_syllabus_files",
        "objective": "Build a deep syllabus from attached course materials.",
        "instance_id": "default",
        "course_id": "harness-course",
        "topic": "Introduction to Algorithms",
        "attachments": [str(_FIXTURES / "learn" / "course_notes.md")],
        "max_turns": 1,
        "acceptance": {
            "syllabus_min_nodes": 8,
            "syllabus_min_subunits": 5,
            "course_active": True,
        },
    },
    "habit_tracker": {
        "description": "Build CLI habit tracker with tests",
        "surface": "code",
        "template_id": "tpl.code.habit",
        "objective": (
            "Build CLI habit tracker: habit.py, tests/test_habit.py, README.md. "
            "Support add/tick/list commands."
        ),
        "deterministic_habit": True,
        "max_turns": 5,
        "acceptance": {"habit_tracker": True},
    },
    "research_local": {
        "description": "Offline research report from attachments",
        "surface": "research",
        "template_id": "tpl.research.offline",
        "job_type": "research_local",
        "objective": "Offline research note from attached sources (no web).",
        "topic": "Local-first AI agents",
        "attachments": [str(_FIXTURES / "research" / "source.md")],
        "task_id": "research-harness",
        "deliverable_path": "tasks/research-harness/research/report.md",
        "max_turns": 1,
        "acceptance": {"min_deliverable_chars": 400},
    },
    "writing_short": {
        "description": "Short markdown draft with title",
        "surface": "writing",
        "template_id": "tpl.writing.short",
        "job_type": "write_draft",
        "objective": "Two-paragraph markdown draft with a clear # title.",
        "task_id": "writing-harness",
        "deliverable_path": "tasks/writing-harness/writing/short.md",
        "max_turns": 1,
        "acceptance": {"min_deliverable_chars": 300, "require_title": True},
    },
    "writing_from_sources": {
        "description": "Draft from attached source notes",
        "surface": "writing",
        "template_id": "tpl.writing.from_sources",
        "job_type": "write_from_sources",
        "objective": "Draft a short note from the attached sources.",
        "topic": "Local-first agents",
        "attachments": [str(_FIXTURES / "research" / "source.md")],
        "task_id": "writing-from-sources",
        "deliverable_path": "tasks/writing-from-sources/writing/from_sources.md",
        "max_turns": 1,
        "acceptance": {"min_deliverable_chars": 300, "require_title": True},
    },
    "learn_corpus_retrieve": {
        "description": "Index mini-book and retrieve planted fact",
        "surface": "learn",
        "template_id": "tpl.learn.index_corpus",
        "job_type": "learn_index_corpus",
        "objective": "Index the attached mini-book into the course corpus.",
        "instance_id": "default",
        "course_id": "corpus-course",
        "topic": "Mini book",
        "attachments": [str(_FIXTURES / "learn" / "mini_book.md")],
        "max_turns": 1,
        "acceptance": {
            "corpus_complete": True,
            "corpus_retrieve_contains": "LACERTA_PLANTED_FACT_QUOKKA",
            "corpus_retrieve_query": "What is the secret mascot animal?",
        },
    },
    "learn_corpus_structured": {
        "description": "Index mini-STEM and retrieve planted table cell",
        "surface": "learn",
        "template_id": "tpl.learn.index_corpus",
        "job_type": "learn_index_corpus",
        "objective": "Index the attached STEM notes into the course corpus.",
        "instance_id": "default",
        "course_id": "corpus-stem-course",
        "topic": "Mini STEM",
        "attachments": [str(_FIXTURES / "learn" / "mini_stem.md")],
        "max_turns": 1,
        "acceptance": {
            "corpus_complete": True,
            "corpus_retrieve_contains": "LACERTA_TABLE_CELL_42",
            "corpus_retrieve_query": "planted cell reference values Quantity",
        },
    },
    "learn_quiz_roundtrip": {
        "description": "Build syllabus then generate+grade practice quiz honestly",
        "surface": "learn",
        "template_id": "tpl.learn.syllabus_files",
        "job_type": "learn_syllabus_files",
        "objective": "Build a syllabus so practice quiz can target a node.",
        "instance_id": "default",
        "course_id": "quiz-roundtrip-course",
        "topic": "Introduction to Algorithms",
        "attachments": [str(_FIXTURES / "learn" / "course_notes.md")],
        "max_turns": 1,
        "acceptance": {
            "course_active": True,
            "syllabus_min_nodes": 3,
            "quiz_roundtrip": True,
        },
    },
    "learn_tutor_grounded": {
        "description": "Index mini-book then tutor teaches planted fact",
        "surface": "learn",
        "template_id": "tpl.learn.index_corpus",
        "job_type": "learn_index_corpus",
        "objective": "Index the attached mini-book into the course corpus.",
        "instance_id": "default",
        "course_id": "tutor-grounded-course",
        "topic": "Mini book",
        "attachments": [str(_FIXTURES / "learn" / "mini_book.md")],
        "max_turns": 1,
        "acceptance": {
            "corpus_complete": True,
            "tutor_reply_contains": "LACERTA_PLANTED_FACT_QUOKKA",
            "tutor_query": "What is the secret mascot animal?",
            "tutor_require_teach": True,
        },
    },
    "learn_archive_chat": {
        "description": "Index mini-book then archive answers from sources",
        "surface": "learn",
        "template_id": "tpl.learn.index_corpus",
        "job_type": "learn_index_corpus",
        "objective": "Index the attached mini-book into the course corpus.",
        "instance_id": "default",
        "course_id": "archive-chat-course",
        "topic": "Mini book",
        "attachments": [str(_FIXTURES / "learn" / "mini_book.md")],
        "max_turns": 1,
        "acceptance": {
            "corpus_complete": True,
            "archive_reply_contains": "LACERTA_PLANTED_FACT_QUOKKA",
            "archive_query": "What is the secret mascot animal?",
            "archive_require_synthesize": True,
        },
    },
    "research_corpus_bulk": {
        "description": "Bulk attachments via shared corpus retrieve",
        "surface": "research",
        "template_id": "tpl.research.offline",
        "job_type": "research_local",
        "recipe_id": "research.offline_corpus",
        "use_corpus": True,
        "objective": "What is the secret research token?",
        "topic": "secret research token",
        "attachments": [
            str(_FIXTURES / "research" / "bulk" / "part_a.md"),
            str(_FIXTURES / "research" / "bulk" / "part_b.md"),
            str(_FIXTURES / "research" / "bulk" / "part_c.md"),
            str(_FIXTURES / "research" / "bulk" / "part_d.md"),
        ],
        "task_id": "research-bulk",
        "deliverable_path": "tasks/research-bulk/research/report.md",
        "max_turns": 1,
        "acceptance": {
            "min_deliverable_chars": 200,
            "task_corpus_complete": True,
            "deliverable_contains": "LACERTA_RESEARCH_PLANTED_ZEBRA",
        },
    },
}
